### ISSUE TITLE
make: ***  No rule to build target « /usr/lib64/libQt5PlatformSupport.a », required for « libqgnomeplatform.so ». Stopping.

### ISSUE THREAD

**Issue by Dremor** [FedoraQt/QGnomePlatform#1]
I was trying to compile this on OpenSUSE Tumbleweed, and I got this error when using the "make" command.

**Comment by MartinBriza** [comment]
You need the private platformsupport-private headers to compile. Not sure how to get them in SUSE though.

**Comment by Dremor** [comment]
Is there a way to download them somewhere?

**Comment by MartinBriza** [comment]
Not easily. They should probably be shipped by your distribution. In Fedora, they're included in the -devel packages.

**Comment by orschiro** [comment]
I had the same problem on Linux Mint 18.3 Cinnamon. I had to install the package `qtbase5-private-dev`.
