### ISSUE TITLE
XDG Portal File Picker runs under xwayland 

### ISSUE THREAD

**Issue by q234rty** [FedoraQt/QGnomePlatform#100]
I guess the culprit is https://github.com/FedoraQt/QGnomePlatform/blob/debe4f8a1cf51ec41285268ff50e046d0ef66729/src/theme/qxdgdesktopportalfiledialog.cpp#L168

**Comment by CoelacanthusHex** [comment]
Oh, it will lead to a terrible experience in a scaled Wayland.
The File Dialog will be blurred.

**Comment by grulja** [comment]
It doesn't mean it will run as xwayland application, this is just an identifer for the parent window, which unfortunately doesn't work on Wayland.

**Comment by q234rty** [comment]
> It doesn't mean it will run as xwayland application, this is just an identifer for the parent window, which unfortunately doesn't work on Wayland.

However it does run as xwayland application: can reproduce on both GNOME 42 and sway with both shotcut and nheko. Just run xeyes and see the eyeball rolling.

**Comment by grulja** [comment]
Ok, I will check.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/QGnomePlatform/commit/d81b57be5acc3f7fa4aa80888ebc391afae89e68.
