### ISSUE TITLE
 Unmatching icons

### ISSUE THREAD

**Issue by re-hub** [FedoraQt/QGnomePlatform#106]
I was wondering how to change the icon theme. Mine looks like this:

![](https://user-images.githubusercontent.com/71829000/183781461-ba7d383c-93e8-45f8-94e7-0ac3092a36af.png)

I am using Gnome 42.4 on archlinux

I tried changing org > gnome > desktop > interface > icon-theme in dconf editor but even though it is already "Adwaita" without alteration, kde apps do not honour it.

**Comment by grulja** [comment]
I usually configure icons and theme with gnome-tweaks.

Can you run any Qt app in a terminal with `QT_LOGGING_RULES='qt.qpa.qgnomeplatform*.debug=true'`? 

For example `QT_LOGGING_RULES='qt.qpa.qgnomeplatform*.debug=true' partitionmanager` and include here the output? It should say what icon theme it loaded.

**Comment by re-hub** [comment]
Thanks for looking into this!

It says "Adwaita" for icon theme but that is not what the programme uses, it is still breeze-light icons.

The output is:

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.qgnomeplatform: String name:  "Noto Sans 12"
qt.qpa.qgnomeplatform: Font name:  "Noto Sans"  (size  12 )
qt.qpa.qgnomeplatform: String name:  "Hack 12"
qt.qpa.qgnomeplatform: Monospace font name:  "Hack"  (size  12 )
qt.qpa.qgnomeplatform: String name:  "Noto Sans 12"
qt.qpa.qgnomeplatform: TitleBar font name:  "Noto Sans"  (size  12 )
qt.qpa.qgnomeplatform: Cursor blink time:  1200
qt.qpa.qgnomeplatform: Double click time:  400
qt.qpa.qgnomeplatform: Long press time:  500
qt.qpa.qgnomeplatform: Double click distance:  5
qt.qpa.qgnomeplatform: Dnd drag threshold:  8
qt.qpa.qgnomeplatform: Password hint timeout:  0
qt.qpa.qgnomeplatform: Icon theme:  "Adwaita"
qt.qpa.qgnomeplatform: Theme name:  "Adwaita-dark"
qt.qpa.qgnomeplatform: Dark version:  yes
Loaded backend plugin:  "pmsfdiskbackendplugin"
"Using backend plugin: pmsfdiskbackendplugin (1)"
"Scanning devices..."
"Device found: SAMSUNG MZVLB256HAHQ-000L7"
getting temp failed for  "/dev/nvme0n1" :  Success
getting powered on time failed for  "/dev/nvme0n1" :  Success
getting power cycles failed for  "/dev/nvme0n1" :  Success
unknown file system type  ""  on  "/dev/nvme0n1p2"
62339175 51466628 4096
144895 22982 4096
"Partition ‘/dev/nvme0n1p3’ is not properly aligned (last sector: 498,953,016, modulo: 825)."
"Device found: SAMSUNG MZVLB256HBHQ-00000"
getting temp failed for  "/dev/nvme1n1" :  Success
getting powered on time failed for  "/dev/nvme1n1" :  Success
getting power cycles failed for  "/dev/nvme1n1" :  Success
"Device found: HGST HTS721010A9E630"
69395711 69370693 4096
"Device found: zram0"
smartctl initialization failed for  "/dev/zram0" :  No such file or directory
error during smart output parsing for  "/dev/zram0" :  No such file or directory
"Scan finished."
```

**Comment by re-hub** [comment]
I can change the icon theme to breeze dark through gnome tweaks but not to Adwaita. In addition, there is no fallback icon theme so if I choose breeze-dark some icons are just missing in other programmes.

**Comment by petersaints** [comment]
I think that this issue should be reopened. As someone else mentioned here a couple of months ago, this is still an issue: https://www.reddit.com/r/gnome/comments/111w66x/how_to_fix_broken_darkmode_qt_theming_in_gnome_w/ 

I also just tested this behavior in a fully up-to-date Fedora 38 install and the result is the same.

QtGnomePlatform uses Adwaita icons by default but whenever it needs an icon that does not exist in Adwaita it falls back to Breeze icons. This would perfectly fine if it detected QGnomePlatform detected that a Dark Theme is being used and it selected the Breeze Dark icon theme instead of the regular Breeze Icon.

**Comment by grulja** [comment]
It is fixed with https://github.com/FedoraQt/QGnomePlatform/pull/137 (I referenced a wrong bug there) and with https://codereview.qt-project.org/c/qt/qtbase/+/476542.
