### ISSUE TITLE
[Feature request] Allow simultaneous build of QT6 and QT5

### ISSUE THREAD

**Issue by werdahias** [FedoraQt/QGnomePlatform#109]
It would be nice if the build would allow for simultaneous building of the QT5 and QT6 feature since some applications are already switching to qt6.

**Comment by hmaarrfk** [comment]
This is somewhat dooable with a little bit of work already, i've been working toward this in:
https://github.com/conda-forge/qgnomeplatform-feedstock/tree/qt6/recipe

You can see the main branch works for qt5, and the branch i liked to qt6 works for qt6. They are in theory co-installable.

**Comment by werdahias** [comment]
For debian I used two separate builds, one with QT5 and one with QT6.
