### ISSUE TITLE
[Bug] Theme not applied on Hyprland

### ISSUE THREAD

**Issue by werdahias** [FedoraQt/QGnomePlatform#123]
I installed qgnomeplatform on Debian with the Hyprland window manager. The environment variable is set in my` .bashrc`.
Yet the theme is not being applied to Qt programs like VLC or Nextcloud. Prefacing them with `QT_QPA_PLATFORMTHEME='gnome'  ` also does not work. Let me know if you need any help debugging. I suspect this is because `XDG_CURRENT_DESKTOP` is set to Hyprland:

```
cat /etc/enviroment
export XDG_CURRENT_DESKTOP=Hyprland
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=Hyprland
export GDK_BACKEND=wayland

```
This might result in the theme never being applied in the first place.

Cheers

**Comment by grulja** [comment]
Does it work on any other application? QGnomePlatform will get used automatically with `XDG_CURRENT_DESKTOP=GNOME` or when you export `QT_QPA_PLATFORMTHEME=gnome`. Do you also have Adwaita-qt installed? Because QGnomePlatform itself doesn't change look of apps itself, it will just apply configuration like fonts, icons, etc.

**Comment by werdahias** [comment]
sorry for the delay. libadwaitaqt1 is installed. Prefacing e.g. vlc with `QT_QPA_PLATFORMTHEME=gnome` or `XDG_CURRENT_DESKTOP=GNOME ` (or both) does not work. 
The relevant files are also installed in the correct directory:

```
apt-file list qgnomeplatform-qt5
qgnomeplatform-qt5: /usr/lib/x86_64-linux-gnu/libqgnomeplatform.so
qgnomeplatform-qt5: /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgnomeplatformtheme.so
qgnomeplatform-qt5: /usr/lib/x86_64-linux-gnu/qt5/plugins/wayland-decoration-client/libqgnomeplatformdecoration.so

```

**Comment by werdahias** [comment]
working fine again for some reason.
