### ISSUE TITLE
Integration for QML applications

### ISSUE THREAD

**Issue by JBBgameich** [FedoraQt/QGnomePlatform#129]
Qt Quick Controls 2 applications use the `Default` style if no other style is set, and that one is really basic  and sometimes not usable.

It would be nice if QGnomePlatform would set this to `org.kde.desktop`, which just passes through the widget style (for example Adwaita-Qt).

A simply copy-paste from [Plasma Integration](https://invent.kde.org/plasma/plasma-integration/-/blob/master/src/platformtheme/kdeplatformtheme.cpp#L578-L581) should be enough.

**Comment by emericg** [comment]
This seems to break every QML applications if KDE is not installed.
And you can actually have Qt or QML applications without KDE.

`QQmlApplicationEngine failed to load component`
`qrc:/qml/DesktopApplication.qml: module "org.kde.desktop" is not installed`

**Comment by JBBgameich** [comment]
Is this on Qt5 or Qt6?
I thought at least on Qt5 there was a fallback if the style was not installed.

**Comment by JBBgameich** [comment]
Btw this doesn't mean it requires KDE, but it requires the desktop style which is made by KDE. However I should fix QGnomePlatform to not set the style if it's not installed on Qt6.

**Comment by emericg** [comment]
Do you know what package usually install that style? Maybe I can try installing it and see what happen.

**Comment by JBBgameich** [comment]
The Qt6 version is probably not yet packaged anywhere. I'll just remove the styling functionality for Qt6 for now.

**Comment by emericg** [comment]
Alright, thanks for the quick response with this issue.
