### ISSUE TITLE
Set Icon theme to dark when GNOME's/xdg-desktop-portal's `org.freedesktop.appearance` is set to prefer dark

### ISSUE THREAD

**Issue by RushingAlien** [FedoraQt/QGnomePlatform#144]
This issue mostly effect Qt Apps that expect the Platform to choose the icon for them, i.e most KDE apps, such as Okular : 

![gambar](https://github.com/FedoraQt/QGnomePlatform/assets/80886145/9aeb6677-33a7-4db5-83b3-31491206e46b)

as you can see, icon theme is stuck on Breeze, instead of using Breeze Dark

**Comment by grulja** [comment]
This has been fixed with https://github.com/FedoraQt/QGnomePlatform/pull/137, but also needs a fix in KDE Frameworks, particulary this one https://invent.kde.org/frameworks/kiconthemes/-/commit/acc39d9468ad25d3881b49d48de71c55b4e73ab4.
