### ISSUE TITLE
Icons in menus and buttons

### ISSUE THREAD

**Issue by FalkAlexander** [FedoraQt/QGnomePlatform#17]
With GTK, icons are not displayed in buttons and menus, but qt does this.
QGnomePlatform does not use the GTK setting, but it should.
(E.g. in qt5ct this can be set.)
In addition, the GNOME like arrangement should be used for dialog buttons ("OK" button always on the right etc.)
![qtgnome](https://cloud.githubusercontent.com/assets/5732964/21265424/b7e18930-c3a1-11e6-985f-31600dee8f7b.png)

**Comment by MartinBriza** [comment]
Thanks for the report.
Can you please state the versions of qgnomeplatform and adwaita-qt packages you use?
Also please tell me which application is this so I can test in the same environment.

**Comment by falkse** [comment]
qgnomeplatform: 0.0.51-1
adwaita-qt: from git (commit 278333a)
Application: Teamspeak 3 (icons in context menus + buttons), cmake-gui (icons in context menu), etc.

Note: The button arrangement is my mistake.

**Comment by polter-rnd** [comment]
Confirm this issue, I have the latest qgnomeplatform version on Fedora 25 (20161024git.fc25), adwaita-qt5 0.97.

**Comment by grulja** [comment]
Icons in menus should be disabled with Qt::AA_DontShowIconsInMenus in adwaita-qt.

**Comment by FalkAlexander** [comment]
Indeed, this issue does not persist anymore with my current configuration.
qgnomeplatform 0.6.0
adwaita-qt5 1.1.1
