### ISSUE TITLE
The return of "GtkDialog mapped without a transient parent" message

### ISSUE THREAD

**Issue by rokm** [FedoraQt/QGnomePlatform#23]
Hello,

on my Fedora 25 installations, I have lately seen Qt applications print the following message to terminal whenever a native dialog (e.g., a file chooser) is opened:
```
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
```

At first I thought the QGnomePlatform is missing a filter for this message (along the lines of the Qt's own gtk3 code), but that is not the case. It has the custom log handler with filter installed, however, the log handler is never called for this specific message.

It turns out that GLib has new (?) logging system, called structured logging, which is used by gtk3, and bypasses the old-style log handler.

So the message can be silenced again by installing a custom log writer that matches and discards it. The only problem is that the docs for ```g_log_set_writer_func()``` are discouraging that sort of approach:
```
Libraries **must not** call this function — only programs are allowed to install a writer function, as there must be a single, central point where log messages are formatted and outputted.
```

Any ideas?

**Comment by MartinBriza** [comment]
Thanks for doing the research on this message. I'd say we're probably safe to just leave it there. Since this is GLib, which is the base for many libraries and apps that utilize Qt for the UI and GLib for the backend (package installers, polkit agents and likely a lot more), I don't think it's wise to touch this.

**Comment by grulja** [comment]
This should be actually already fixed with https://github.com/FedoraQt/QGnomePlatform/commit/9c893cd07c5cbc1d15aed676d6e2b43314eea4af.
