### ISSUE TITLE
DPI scaling appears to be applied twice

### ISSUE THREAD

**Issue by auscompgeek** [FedoraQt/QGnomePlatform#24]
I have my text scaling factor set to 1.25 in GNOME. With QGnomePlatform, text appears too large. This doesn't happen with qt5ct or QGtkStyle.

Setting the DPI to 96 in KDE System Settings makes the text size consistent with GNOME, but then obviously the correct DPI won't be used in KDE…

**Comment by MartinBriza** [comment]
Yeah, the problem with text scaling in Qt is that the font sizes are not
scaled linearly. We need to find a proper solution, so this is a valid
report.

2017-05-03 15:59 GMT+02:00 David Vo <notifications@github.com>:

**Comment by Venemo** [comment]
@MartinBriza For interested parties who might want to help contribute to this issue, could you give us a clue about what might be the problem here and how to fix it?

**Comment by leidav** [comment]
The font scaling seems to be applied twice. 
When i change
` gdouble scaling = g_settings_get_double(m_settings, "text-scaling-factor");`
to
`gdouble scaling = 1.0;`
the correct font scaling (1.25 on my system) is applied.

**Comment by auscompgeek** [comment]
Nice catch. I'm guessing something else is already picking up the correct DPI settings, so then scaling the font sizes ourselves is the wrong thing to do.

**Comment by h4tr3d** [comment]
Qt 5.6 just introduce new HiDPI handling. It uses system-wide information for proper scaling: xrandr info, Xft.dpi (it uses by libxcursor that uses by Qt5 and currently it work wrong. I have idea how to fix it but have no time for it temporally). When you configure `text-scale-factor` it also affect xrandr settings (`xdpyinfo | grep -B2 resolution`). Qt just load this information and apply valid scaling. When additional up-scaling is applied fonts just looks huge.

My current solution: enable scaling for Qt < 5.6 (Qt4 inclusive) and force 1.0 for Qt >= 5.6:
https://github.com/h4tr3d/QGnomePlatform/commit/6b6af5cc061e660757b0039196691360f495a272

**Comment by grulja** [comment]
Fixed in master.
