### ISSUE TITLE
Does not work in Cinnamon

### ISSUE THREAD

**Issue by h4tr3d** [FedoraQt/QGnomePlatform#33]
Settings schema is hardcoded and points to `org.gnome.desktop.interface`. Under Cinnamon scheme is `org.cinnamon.desktop.interface` but it does not contains `monospace-font-name` that reused from Gnome schema.

Seems, that two settings provides is needed: main and fallback. Main must be configured using `XDG_SESSION_DESKTOP` (or `DESKTOP_SESSION`) environment variables. Fallback must be configured to the Gnome always.

If Main settings sets construction fails or current desktop is a Gnome, just make it pointed to Fallback one.

If Main settings set does not contain some property, request it from Fallback one.

PS I know, that PR is a best report, but time... :-)

**Comment by h4tr3d** [comment]
Fixes by https://github.com/h4tr3d/QGnomePlatform/commit/b48679798f4266007045b0a023ae69eba9939d09

**Comment by grulja** [comment]
Cinnamon support has been merged to master.
