### ISSUE TITLE
Not working with VirtualBox 5.2.2 r119230 (Qt5.6.1)

### ISSUE THREAD

**Issue by orschiro** [FedoraQt/QGnomePlatform#34]
Dear all, 

I am trying to understand why the latest version of VirtualBox doesn't pick up the style. 

See the below screenshot. Any ideas or advice?

Thank you!

![image](https://user-images.githubusercontent.com/170947/34095533-0c7b1a64-e3d2-11e7-956a-7d66bc570dfe.png)

**Comment by h4tr3d** [comment]
Try run:
```
env QT_QPA_PLATFORMTHEME=gnome QT_LOGGING_RULES="*=true" strace -o /dev/null VirtualBox
```
and look for lines like:
```
qt.qpa.qgnomeplatform: Theme name:  Arc
qt.qpa.qgnomeplatform: Dark version:  no
qt.qpa.qgnomeplatform: Cursor blink time:  1024
qt.qpa.qgnomeplatform: Double click time:  400
qt.qpa.qgnomeplatform: Long press time:  500
qt.qpa.qgnomeplatform: Double click distance:  5
qt.qpa.qgnomeplatform: Dnd drag threshold:  8
qt.qpa.qgnomeplatform: Password hint timeout:  0
qt.qpa.qgnomeplatform: Icon theme:  Mint-Y
qt.qpa.qgnomeplatform: Font scaling: forced to 1.0 (for Qt>=5.6)
qt.qpa.qgnomeplatform: Font name:  "Noto Sans"  (size  7 )
qt.qpa.qgnomeplatform: Monospace font name:  "Fira Mono"  (size  8 )
```

Note, such call just output Error message. If nothing shows, seems that VBox just overrides some system settings during start. In my case (Manjaro and VBox from repos) platform theme handles correctly.

**Comment by orschiro** [comment]
@h4tr3d thank you! Currently cannot test but expect this to work. Hence closing.
