### ISSUE TITLE
File dialog filter name with parentheses cut at wrong position

### ISSUE THREAD

**Issue by jspitz** [FedoraQt/QGnomePlatform#35]
In [qgtk3dialoghelpers.cpp#L479](https://github.com/MartinBriza/QGnomePlatform/blob/d67dae6082bb5c9000a4055a87c63bcb581b8753/src/qgtk3dialoghelpers.cpp#L479), the filter name is stripped off as follows:
`const QString name = filter.left(filter.indexOf(QLatin1Char('(')));`

This blindly strips off all strings at parentheses, notwithstanding whether these parentheses are part of the name (as in "My File Format (Version 2)") or, as is the intended case, hold the suffixes. So "My File Format (Version 2) (*.mff)" is displayed as "My File Format" rather than "My File Format (Version 2)". This is a major usability problem with apps proposing multiple versions of a format to select from.

I suggest that you use the regexp from `QPlatformFileDialogHelper` instead, as in (untested):
```
QRegExp rx("^(.*)\\(([a-zA-Z0-9_.,*? +;#\\-\\[\\]@\\{\\}/!<>\\$%&=^~:\\|]*)\\)$");

foreach (const QString &filter, filters) {
        GtkFileFilter *gtkFilter = gtk_file_filter_new();
        QString name = filter
        int i = rx.indexIn(filter);
        if (i >= 0)
            name = regexp.cap(1);
        const QStringList extensions = cleanFilterList(filter);

        gtk_file_filter_set_name(gtkFilter, name.isEmpty() ? extensions.join(QStringLiteral(", ")).toUtf8() : name.toUtf8());
        foreach (const QString &ext, extensions)
            gtk_file_filter_add_pattern(gtkFilter, ext.toUtf8());

        gtk_file_chooser_add_filter(GTK_FILE_CHOOSER(gtkDialog), gtkFilter);

        _filters.insert(filter, gtkFilter);
        _filterNames.insert(gtkFilter, filter);
}

**Comment by jspitz** [comment]
A simpler solution, but probably not as accurate, would be
`const QString name = filter.left(filter.lastIndexOf(QLatin1Char('(')));`

**Comment by jspitz** [comment]
Since this seems to be no longer active, I've reported this issue now at https://github.com/CrimsonAS/gtkplatform/issues/37 as well. Feel free to close.

**Comment by grulja** [comment]
This should be fixed now as we default to QXdgDesktopPortalFileDialog where it's possible.

**Comment by jspitz** [comment]
A belated confirmation that this is indeed fixed (v. 0.7. only made it today to my distribution). Thanks!
