### ISSUE TITLE
QGnomePlatform breaks QtQuick MessageDialog rendering 

### ISSUE THREAD

**Issue by cgutman** [FedoraQt/QGnomePlatform#42]
When QGnomePlatform is active, all QtQuick dialogs fail to render, only showing black. This happens for me with Qt 5.11.3 and Qt 5.12.1, possibly other versions too.

![dialog-bug](https://user-images.githubusercontent.com/2695644/53292799-73844a00-377d-11e9-8a29-d6cea1e6343f.png)

Calling `QGuiApplication::setDesktopSettingsAware(false)` works around the issue. Attached is a minimal reproducer.

QGnomePlatform package: qgnomeplatform-0.5-6.fc29.x86_64
Qt package: qt5-qtbase-5.11.3-1.fc29.x86_64

Minimal reproducer: [dialog-bug.zip](https://github.com/FedoraQt/QGnomePlatform/files/2897367/dialog-bug.zip)

Downstream user-reported bug: https://github.com/moonlight-stream/moonlight-qt/issues/161

**Comment by MartinBriza** [comment]
Hm, this may actually be an issue of the widget style, not the theme itself. Can you try if this happens if you use `QT_STYLE_OVERRIDE=breeze` (in case you have breeze installed of course)?

**Comment by cgutman** [comment]
I tried several different `QT_STYLE_OVERRIDE` values and couldn't get anything to change. I even straced it and couldn't find it attempting load anything that I tried to specify in `QT_STYLE_OVERRIDE`.

The only thing that I could do to make it change behavior was specifying `-platformtheme qt5ct` which also fixed the dialog rendering (albeit with a different theme).

Is there anything else I can do to get more debugging output from Qt or QGnomePlatform? It just seemed to silently choose the next platform theme and styles if I specified one that was invalid.

**Comment by cgutman** [comment]
I made some progress. It seems the problem is with QGnomePlatformTheme's palette.

Changing `palette()` to also call through to QPlatformTheme for `QPlatformTheme::SystemPalette` rather than using `GnomeHintsSettings::palette()` fixes the rendering:
```
const QPalette *QGnomePlatformTheme::palette(Palette type) const
{
    return QPlatformTheme::palette(type);
}
```

However, I'm also a bit confused by `GnomeHintsSettings::loadPalette()`. It appears that all it does is just load a default-constructed QPalette and do nothing. That seems like the wrong thing to do. If we're not going to change the QPalette, why even bother returning one?

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/QGnomePlatform/commit/d4277c9109d17ec53b369a2cd938b9925bf11294.
