### ISSUE TITLE
Doesn't work on Ubuntu

### ISSUE THREAD

**Issue by joshirio** [FedoraQt/QGnomePlatform#43]
Tested on Ubuntu 18.04 and 19.04, it seems that the system is not able to find the QGnomePlatform style.

```
$ qtcreator -style gnome
QApplication: invalid style override passed, ignoring it.
```

I also tried with style `gtk3` and `qgnomeplatform` with the same result.

And this also with `QT_QPA_PLATFORMTHEME='gnome'` but  Qt apps present the fusion style and the manual style override fails to find the theme.
```
$ cat /etc/profile.d/use-qt-gtk.sh 
export QT_QPA_PLATFORMTHEME=gnome
```

Maybe I'm doing something wrong on my side.
Thanks.

**Comment by Lin-Buo-Ren** [comment]
Have you tried running with the `QT_DEBUG_PLUGINS=1` environment variable?

**Comment by grulja** [comment]
QGnomePlatform is a platform theme, not a widget style, this means that it will just say the app what style, font, icons etc. to use. If you want a gtk widget style, you need to install adwaita-qt for example.

**Comment by joshirio** [comment]
> Have you tried running with the `QT_DEBUG_PLUGINS=1` environment variable?

```
Got keys from plugin meta data ("xcb_glx")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/xcbglintegrations" ...
loaded library "/usr/lib/x86_64-linux-gnu/qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so"
QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgnomeplatform.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgnomeplatform.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformThemeFactoryInterface.5.1",
    "MetaData": {
        "Keys": [
            "gnome",
            "gtk3",
            "qgnomeplatform"
        ]
    },
    "className": "QGnomePlatformThemePlugin",
    "debug": false,
    "version": 329989
}


Got keys from plugin meta data ("gnome", "gtk3", "qgnomeplatform")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platformthemes" ...
loaded library "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgnomeplatform.so"
```
Full debug output can be found [here](https://gist.github.com/joshirio/cea66dfecf491a6fad7321771faf4a55).
So the plugin is found and loaded, but the look doesn't change.



> QGnomePlatform is a platform theme, not a widget style, this means that it will just say the app what style, font, icons etc. to use. If you want a gtk widget style, you need to install adwaita-qt for example.

Ok, thanks for pointing this out.
The issue is still that with the proper env export (QT_QPA_PLATFORMTHEME) nothing changes though, the default fusion theme is still shown.

**Comment by grulja** [comment]
Look here: https://github.com/FedoraQt/QGnomePlatform/blob/master/src/gnomehintssettings.cpp#L299

You can see the order of themes which will be picked by the app based on availability. That means that it will first try to use "adwaita-qt" style, if it's not found, it will use "fusion" (your case). You just need to install "adwaita-qt" style and things will start magically work for you.

**Comment by joshirio** [comment]
Right, now I get it, I thought this was a replacement for the QGTKStyle but for GTK3.
Thanks for your help.
