### ISSUE TITLE
Build Failure on Qt 5.13

### ISSUE THREAD

**Issue by SolarAquarion** [FedoraQt/QGnomePlatform#48]
i think it needs this patch https://github.com/amezin/QGnomePlatform/commit/cae92e0d124bf2305b7ecccf8865e84545ed66a2

**Comment by grulja** [comment]
Can you submit a pr?

**Comment by SolarAquarion** [comment]
did it

**Comment by grulja** [comment]
Can be closed now. Will be fixed when a new stable release is out.
