### ISSUE TITLE
Override system theme

### ISSUE THREAD

**Issue by jeffshee** [FedoraQt/QGnomePlatform#49]
Hi, is there any way to override current system theme if some applications doesn't work well? I'm using Adwaita dark, and this WPS Office seems hard-coded the UI, make it unusable with dark theme. The apps look fine if I use Adwaita Light though.

Please suggest how could I workaround this kind of issue. 
![Screenshot from 2019-10-06 11-31-40](https://user-images.githubusercontent.com/25530920/66263391-049bc300-e82d-11e9-9a1e-4ee68c4c9cc7.png)

**Comment by grulja** [comment]
You can use "application -style adwaita", which should use the light theme or "application -style adwaita-dark" to use the dark variant.

**Comment by MartinBriza** [comment]
The most convient way to do this is to copy the application's `.desktop` file (that's probably located in `/usr/share/applications` to `~/.local/share/applications` and modify it to use the argument @grulja mentioned in the `Exec=` line or run it with `QT_STYLE_OVERRIDE=adwaita` in the environment.

**Comment by jeffshee** [comment]
Thanks, I tried `wps -style=adwaita` and this is what I get:
![Screenshot from 2019-10-08 11-23-43](https://user-images.githubusercontent.com/25530920/66362534-20829e80-e9be-11e9-91ff-a554c5b728ff.png)
I'm not sure why the theme is broken this time. Usable if compare to previous one though.

`QT_STYLE_OVERRIDE=adwaita` doesn't work, it's still using the system theme. This work fine on other QT apps (vlc for example), can't figure out why.
