### ISSUE TITLE
GDK 3.0 not in include path of `common` subpackage

### ISSUE THREAD

**Issue by Jaakkonen** [FedoraQt/QGnomePlatform#53]
Build fails with glib2's `gio/gio.h` or gdk3's `gdk/gdk.h` not being found with the upstream code.

On my machine I managed to fix this by adding `gdk-3.0` to the `PKGCONFIG` section of the `common.pro`. It seems that the `gtk+-3.0` include doesn't create `glib2` or `gdk3` includes to the CC flags at least on Arch Linux.

Should the `gdk-3.0` be added to the PKGCONFIG to enable better out-of-the-box compability more systems?

**Comment by morealaz** [comment]
It seems that recent compile errors in Arch Linux are related to recently [Xorg cleanup](https://www.archlinux.org/news/xorg-cleanup-requires-manual-intervention/) in Arch, which removed `xorgproto` from Arch and caused all these weird errors. It came back again in Arch repository and after system upgrade all those errors gone away.
see [here](https://lists.archlinux.org/pipermail/arch-dev-public/2019-December/029767.html).

**Comment by Jaakkonen** [comment]
Yep, the problems were caused because of the `Xorg` headers missing due to `xorgproto` not being a dependency of all packages utilizing those headers. The issue isn't in QGnomePlatform so I'll close this issue.
