### ISSUE TITLE
Qt can't find the Semi-Light variant of Fira Sans

### ISSUE THREAD

**Issue by guihkx** [FedoraQt/QGnomePlatform#55]
I don't know if this is an issue you guys can/should fix, but I decided to report anyway...

So, my font settings on GNOME Tweaks looks like this:

![Screenshot from 2020-02-29 16-30-55](https://user-images.githubusercontent.com/626206/75613848-e3f04480-5b10-11ea-8fee-e2b27de941e0.png)

The "problematic" font is the one set for **Interface Text**, which is displayed as **Fira Sans Book 10** in the screenshot, but it's actually saved with a different name in dconf (don't know why, tbh):

```
$ gsettings get org.gnome.desktop.interface font-name
'Fira Sans Semi-Light 10'
```

However, when I launch any Qt program, that font doesn't get picked up. Well, actually it's the **Semi-Light** variant that doesn't get picked up, because if I go back to GNOME Tweaks and set the **Interface Text** font to **Fira Sans Regular 10**, then Qt is able to pick up the font properly.

Here's how I found out:

```
$ env QT_QPA_PLATFORMTHEME=gnome QT_LOGGING_RULES="*=true" qbittorrent
[... very long output ...]
qt.text.font.match: QFontDatabase::match
  request:
    family: Fira Sans Semi-Light [-- any --], script: 2
    weight: 50, style: 0
    stretch: 0
    pixelSize: 13
    pitch: *
qt.text.font.match:   NO MATCH FOUND

qt.text.font.match: QFontDatabase::match
  request:
    family: Bitstream Vera Sans [-- any --], script: 2
    weight: 50, style: 0
    stretch: 0
    pixelSize: 13
    pitch: *
qt.text.font.match:   REMARK: looking for best foundry for family 'Bitstream Vera Sans' [1]
qt.text.font.match:           looking for matching style in foundry 'Bits' 4
qt.text.font.match:           best style has distance 0x0
qt.text.font.match:           found smoothly scalable font (13 pixels)
qt.text.font.match:           found a match: score 0 best score so far ffffffff
qt.text.font.match: returning box engine
[... more output ...]
```

Is there any workarounds to this? Thanks!

**Comment by grulja** [comment]
I got a suggestion to use [qt_fontFromString](https://github.com/FedoraQt/QGnomePlatform/blob/f486a46900b1f8e6b49b32409d6a69077e24faef/src/theme/qgtk3dialoghelpers.cpp#L608-L631). I will check and try if it fixes this issue.

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/QGnomePlatform/commit/f356aa2ce5fb12688797560b3e2e4471bd6b0b0f.
