### ISSUE TITLE
Remove fallback to breeze

### ISSUE THREAD

**Issue by ilya-fedin** [FedoraQt/QGnomePlatform#56]
Currently, QGnomePlatform [fallbacks to breeze icon theme](https://github.com/FedoraQt/QGnomePlatform/blob/f6c95fe47caf4e9694ab043d44639c0475fde4f3/common/gnomehintssettings.cpp#L458).
Flatpak KDE runtime has breeze theme by default, but host may not. If an app checks if there are some icon in the system, a user uses adwaita, breeze has such icon, but adwaita is not and icon is not displayed by app itself, but app sends icon name to some system component - then user will see a dummy icon or even empty space.
If there will be no fallback to breeze, then icon check will fail and app can fallback to icon that guaranteed to exist (e.g. icon with app id) and everything will be ok.

**Comment by grulja** [comment]
What would you suggest? Fallback to **hicolor**? In Qt the KDE platform theme has fallback to **breeze** or **oxygen**, the Gnome one fallbacks to **gnome** and the generic one fallbacks to **hicolor**.

**Comment by ilya-fedin** [comment]
> Fallback to **hicolor**?

To hicolor or gnome, yes.

> the Gnome one fallbacks to **gnome**

https://github.com/FedoraQt/QGnomePlatform/blob/f6c95fe47caf4e9694ab043d44639c0475fde4f3/common/gnomehintssettings.cpp#L458

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/QGnomePlatform/commit/a4a5788e754c0d55980454a60a04963a2ca31aa6.
