### ISSUE TITLE
Why setting a default QPalette?

### ISSUE THREAD

**Issue by memeplex** [FedoraQt/QGnomePlatform#58]
Currently when gtk theme changes a best effort is done to find and set a similar qt theme. Also, a palette is loaded and set but... it's just a default palette created as `QPalette()`. What is the point of that?

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/QGnomePlatform/commit/d4277c9109d17ec53b369a2cd938b9925bf11294.

**Comment by memeplex** [comment]
Looking at your comment:

> This may result into some wrong colors, but it's better than no colors when using empty palette

do you think this may be the reason for

https://github.com/FedoraQt/adwaita-qt/issues/133

?

**Comment by grulja** [comment]
I'm not sure. I tried to reproduce and I can reproduce it, the colors are not correct. However it seems anki is using some web view and I have no idea how that works and where that takes colors from. I will try to look again.

**Comment by memeplex** [comment]
Ok, thanks for taking a look, I'm asking upstream for some guidance, will let you know if they come with something helpful.
