### ISSUE TITLE
Add breeze to list of fallback styles

### ISSUE THREAD

**Issue by memeplex** [FedoraQt/QGnomePlatform#59]
Could you add breeze between adwaita and fusion? It's plasma default, so quite a standard style nowadays.

```
    styleNames << QStringLiteral("adwaita")
               << QStringLiteral("fusion")
               << QStringLiteral("windows");
```

**Comment by grulja** [comment]
I'm not sure this makes sense, because Breeze is a KDE Plasma style, most users won't have it even installed, while both fusion and windows are styles which are part of Qt itself.

**Comment by memeplex** [comment]
I understand many users won't, but my point is to put it in a fallback chain since it's the most representative theme in terms of how a modern qt application looks like, the main target of qt developers and hence the most tested one, while fusion is a very basic and dated default and, let's face it, adwaita-qt has its share of issues with non-trivial applications (and sometimes with trivial ones too).

**Comment by memeplex** [comment]
Ok, there already exists a much better solution than the one I proposed, you can still override the theme for apps that don't work that well with adwaita-qt in the usual way: `QT_STYLE_OVERRIDE=adwaita`.
