### ISSUE TITLE
Font too thick in Fedora 32 beta

### ISSUE THREAD

**Issue by memeplex** [FedoraQt/QGnomePlatform#60]
Please compare gtk and qt fonts:

![image](https://user-images.githubusercontent.com/2845433/78867938-5ad60280-7a18-11ea-9266-daa191c6f9b5.png)

Seems like the same face to me, but in qt it looks bolder. I've also tested this in Arch and there it looks fine.

**Comment by memeplex** [comment]
I realized the problem exists to some extent both in Wayland and XWayland but it's much more noticeable when using the Wayland backend which Fedora sets by default (QT_QPA_PLATFORM=wayland), that's the reason I hadn't noticed it in Arch at first sight. Moreover, doesn't seem to be specific of QGnomePlatform, but maybe there is some font rendering tweak you can do since you strive to achieve similar looks.

**Comment by BjoernDaase** [comment]
FWIW, the same issue was reported against mutter: https://gitlab.gnome.org/GNOME/mutter/-/issues/1168.  
But as the issue seems to happen in sway as well (https://gitlab.gnome.org/GNOME/mutter/-/issues/1168#note_761882), it was closed and identified as a QTish bug.

**Comment by bugaevc** [comment]
> But as the issue seems to happen in sway as well (https://gitlab.gnome.org/GNOME/mutter/-/issues/1168#note_761882)

That was Weston 😀, not Sway

**Comment by BjoernDaase** [comment]
> > But as the issue seems to happen in sway as well (https://gitlab.gnome.org/GNOME/mutter/-/issues/1168#note_761882)
> 
> That was Weston grinning, not Sway

I actually wanted to write Weston but looks like I worked too much with Sway in the last weeks 😅

**Comment by grulja** [comment]
It looks like a bug in the Cantarell font.

See https://bugzilla.redhat.com/show_bug.cgi?id=1823984.

**Comment by grulja** [comment]
There is upstream issue https://gitlab.gnome.org/GNOME/cantarell-fonts/-/issues/41 if anyone wants to comment and help to identify the problem.

**Comment by madig** [comment]
This is not a bug, but Qt purposely using a feature of FreeType called stem-darkening. Basically, Qt 5.9+ is doing it right, everything else is doing it wrong, but I didn't have the time yet to implement something so that all other toolkits can follow along.

See https://www.freetype.org/freetype2/docs/text-rendering-general.html#experimental-stem-darkening-for-the-auto-hinter.

**Comment by bugaevc** [comment]
@madig but it clearly comes out wrong and _less_ readable than without it (see the first screenshot in https://gitlab.gnome.org/GNOME/mutter/-/issues/1168), so maybe there is a bug?

**Comment by madig** [comment]
Wait, maybe we're talking past each other. So, there's two things here:

1. The menu bar text looks a big thicker than the tab text in Chrome in https://user-images.githubusercontent.com/2845433/78867938-5ad60280-7a18-11ea-9266-daa191c6f9b5.png -- that's on purpose.
2. The title bar text of LyX there looks a bit on the thick side, as does the header text in https://gitlab.gnome.org/GNOME/mutter/uploads/5e250f9849e582abfebd8b814ae56367/image.png -- I think that's the actual problem and what https://gitlab.gnome.org/GNOME/cantarell-fonts/-/issues/41 is about.

Sorry if we meant the same thing!

**Comment by bugaevc** [comment]
Yes, I was talking about your second point, which _is_ a bug 😀

This issue was originally filed about your first point, but apparently repurposed to include the second since then.

**Comment by memeplex** [comment]
I don't think the first point isn't related to a problem in font rendering because it surely looks different in three (not two) cases:
1. GTK (Wayland and X11): thin
2. Qt (X11): a bit thick
3. Qt (Wayland): thicker and somewhat blurry (rough on some edges)

**Comment by madig** [comment]
1. and 2. are expected because only Qt 5.9+ renders fonts correctly, all other toolkits have thin rendering. Haven't seen 3.

**Comment by memeplex** [comment]
Well I checked that in Fedora 32 beta and up-to-date Arch some days ago and 2 and 3 were perceptibly different side-to-side, but maybe it was some momentary artifact of both tests being on more or less bleeding-edge software, so I'm going to recheck later since you're not seeing it.

**Comment by memeplex** [comment]
Also @madig, regarding your comment:

> Basically, Qt 5.9+ is doing it right, everything else is doing it wrong, 

while the description of stem darkening in freetype site stated:

> Stem darkening emboldens glyphs at smaller sizes to make them more readable on common low-DPI screens

Now, I have a hidpi screen in my laptop (3000x2000), is it expected to use "stem darkening"  then? Also Cantarell 11 is not particularly tiny at 2x scale.

**Comment by madig** [comment]
Stem darkening decreases in effect with font size, since it is primarily needed in common low DPI environments. There's some stem thickness/pixel size threshold above which there is no darkening at all, I don't remember the value though. I have no idea if Qt does something clever here.

I have never used Wayland so I can't comment on that. If it looks like the title bars in https://gitlab.gnome.org/GNOME/mutter/uploads/5e250f9849e582abfebd8b814ae56367/image.png or https://gitlab.gnome.org/GNOME/mutter/uploads/be37ec363651574aa8d422b9c396aa90/image.png, it is most likely the bug I think we're discussing here.

**Comment by memeplex** [comment]
> I'm going to recheck later since you're not seeing it.

This is Anki in Arch, Wayland vs Qt, 500% zoom (times 2x of scaling factor), no smoothing:

![image](https://user-images.githubusercontent.com/2845433/79644435-5b406d00-817f-11ea-8351-14e0416abb0c.png)

You can see that the fonts below are rendered darker. Also tested it with LyX with identical results. Weirdly enough, while the screenshots above are using Fusion, I'm unable to detect similar differences with AdwaitaQt.

**Comment by madig** [comment]
That's funny. No idea why text is rendered differently, best to ask a Qt and/or Fusion person.

**Comment by memeplex** [comment]
Done here: https://bugreports.qt.io/browse/QTBUG-83636

**Comment by memeplex** [comment]
A fix for this was merged upstream. The reason of the problem was:

> the font gamma value is set to 1.0 like it used to be for xcb

**Comment by madig** [comment]
One bug down, N more to go :)
