### ISSUE TITLE
Maybe just use gtk platform instead of QGnomePlatform

### ISSUE THREAD

**Issue by TomaszGasior** [FedoraQt/QGnomePlatform#61]
First of all, I don't want to say this project is wrong or not needed. It's just my though about "Qt in GNOME" problem.

I wonder whether https://github.com/CrimsonAS/gtkplatform may use better approach than QGnomePlatform does. gtkplatform uses GTK to draw window, titlebar and menubar and uses gtk's drawing area to put window's content rendered by Qt into GTK window. While it has some performance costs for me, end user, it provides better UX. Also, this approach has one advantage: decorations are consistent with GTK apps because they are rendered by GTK as client-side. 

gtkplatform uses Adwaita-Qt style inside Qt-rendered window if Adwaita-Qt is available. Project author even wants to provide some GTK-specific widgets like headerbars into Qt apps. Both projects have the same level of instability. :(

Maybe it may be good idea to drop QGnomePlatform and move forward with https://github.com/CrimsonAS/gtkplatform ? Just asking. :)

Here is comparison between these two projects using KeePassXC as example:
![Zrzut ekranu z 2020-04-13 19-05-23](https://user-images.githubusercontent.com/1395027/79142060-38970880-7dbb-11ea-9329-b0e3d43193c2.png)
![Zrzut ekranu z 2020-04-13 19-06-23](https://user-images.githubusercontent.com/1395027/79142071-3b91f900-7dbb-11ea-8977-facb855e1c1c.png)

**Comment by grulja** [comment]
And maybe not? It's a completely different approach, with performance issues, which might also break easily as it relies heavily on GTK. I don't see reason why we should stop doing what we are doing and keep improving it.

**Comment by TomaszGasior** [comment]
gtkplatform provides better UX for end user. Also, basically I though it may be better to merge manpower for creating one well-tested and solid solution instead two plugins with similar purpose, both buggy and unreliable. No offense, although. Keep going if you want.
