### ISSUE TITLE
Wrong colors applied for the adwaita-qt theme (Qt 5.15)

### ISSUE THREAD

**Issue by guihkx** [FedoraQt/QGnomePlatform#67]
Hello there,

Qt was recently updated to version 5.15 on Arch Linux, and that broke either QGnomePlatform or [adwaita-qt](https://github.com/FedoraQt/adwaita-qt). Although I'm not _exactly_ sure which one, my bet is on QGnomePlatform, because [qt5ct](https://sourceforge.net/projects/qt5ct/) applies the theme _kinda_ okay -- because I still have theming issues on some other programs, such as qBittorrent. But with QGnomePlatform, I never had those.

```
$ QT_QPA_PLATFORMTHEME=gnome QT_LOGGING_RULES="*=true" keepassxc &> qt.log
$ grep platform qt.log
qt.qpa.qgnomeplatform: Font name:  "Cantarell"  (size  11 )
qt.qpa.qgnomeplatform: Monospace font name:  "Source Code Pro"  (size  10 )
qt.qpa.qgnomeplatform: TitleBar font name:  "Cantarell"  (size  11 )
qt.qpa.qgnomeplatform: Cursor blink time:  1200
qt.qpa.qgnomeplatform: Double click time:  400
qt.qpa.qgnomeplatform: Long press time:  500
qt.qpa.qgnomeplatform: Double click distance:  5
qt.qpa.qgnomeplatform: Dnd drag threshold:  8
qt.qpa.qgnomeplatform: Password hint timeout:  0
qt.qpa.qgnomeplatform: Icon theme:  "Papirus-Dark"
qt.qpa.qgnomeplatform: Theme name:  "Adwaita-dark"
qt.qpa.qgnomeplatform: Dark version:  yes
```
\>>> [qt.log](https://gist.github.com/guihkx/d1cd7040495e8eea3c27648f5b27d9da/raw/80c022b79ebc7009d947bd1ee5ec0f81aeb0bdd0/qt.log)

### Before / After

qgnomeplatform + adwaita-qt on Qt 5.14:

![Screenshot from 2020-06-06 23-09-19](https://user-images.githubusercontent.com/626206/83956201-c5959580-a831-11ea-838e-561877e009c3.png)

qgnomeplatform + adwaita-qt on Qt 5.15:

![Screenshot from 2020-06-06 23-05-58](https://user-images.githubusercontent.com/626206/83956199-c4fcff00-a831-11ea-81f2-9c100bf1d286.png)

I'm using the git version of both adwaita-qt and qgnomeplatform. And I've tried recompiling both of them, but it didn't help either.

Thanks!

**Comment by ilya-fedin** [comment]
Similar problem was in lxqt-qtplugin recently: https://github.com/lxqt/lxqt-qtplugin/issues/54#issuecomment-634533001

**Comment by ilya-fedin** [comment]
Probably, reverting https://github.com/FedoraQt/QGnomePlatform/commit/d4277c9109d17ec53b369a2cd938b9925bf11294 can help

**Comment by guihkx** [comment]
> Probably, reverting [`d4277c9`](https://github.com/FedoraQt/QGnomePlatform/commit/d4277c9109d17ec53b369a2cd938b9925bf11294) may help

Didn't work for me...

**Comment by grulja** [comment]
I have a plan with QGnomePlatform and Adwaita, which should solve this issue, but it will take a while to implement it all. I will try to come up with a temporary solution. Expect a patch to test.

**Comment by grulja** [comment]
Can you try [this patch](https://jgrulich.fedorapeople.org/qgnomeplatform.patch)? It basically creates same palette as in Adwaita-qt.

My plan is to turn adwaita-qt into a library so I can depend on it and call some functions from there, for example to get this color palette, but also to render buttons for window decorations etc., but it will take a while to implement it.

**Comment by guihkx** [comment]
Looking really good, IMO:

![Screenshot from 2020-06-09 10-54-04](https://user-images.githubusercontent.com/626206/84139632-998f3580-aa26-11ea-9d88-34bc09554bcd.png)

![Screenshot from 2020-06-09 10-54-28](https://user-images.githubusercontent.com/626206/84139654-a4e26100-aa26-11ea-82ca-eef0dc44545c.png)

**Comment by grulja** [comment]
Thank you for testing. I will push it then.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/QGnomePlatform/commit/367dbfb3583abf7ecd4627213ea2f11fcbed0c06.
