### ISSUE TITLE
Port to CMake

### ISSUE THREAD

**Issue by KAMiKAZOW** [FedoraQt/QGnomePlatform#74]
According to https://www.qt.io/blog/qt-6-build-system CMake is the default build system for Qt6. The page says about qmake: "At the moment the qmake build system is still in place" which doesn't really give confidence that qmake is here for the long haul.

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/QGnomePlatform/commit/0b05cca24741ab818abe3bf6e68b968f4af04728.
