### ISSUE TITLE
Kate won't display the "Open File" or "Save File" dialog anymore on latest master 

### ISSUE THREAD

**Issue by codingtim** [FedoraQt/QGnomePlatform#75]
Hi,

I am having a similar issue as https://github.com/FedoraQt/QGnomePlatform/issues/73
kate does not show the open or save file dialogs.

Manjaro
QGnomePlatform https://github.com/FedoraQt/QGnomePlatform/commit/d5a01ea00ef49c22fa4f623495cd0d31e991a02e
Qt 5.15.1
gnome 3.38.1
kate 20.08.3

QT settings:
QT_AUTO_SCREEN_SCALE_FACTOR=1
QT_QPA_PLATFORMTHEME=gnome
QT_STYLE_OVERRIDE=Fusion

I do not have xdg-desktop-portal-gtk installed (this was asked in the other issue) I also don't know why this has to be installed?
Output of dbus-monitor --session while executing a save:

```
method call time=1606126205.541434 sender=:1.322 -> destination=org.freedesktop.portal.Desktop serial=52 path=/org/freedesktop/portal/desktop; interface=org.freedesktop.portal.FileChooser; member=SaveFile
   string "x11:88080390"
   string "Save File"
   array [
      dict entry(
         string "current_folder"
         variant             array of bytes "/home/tim" + \0
      )
      dict entry(
         string "directory"
         variant             boolean false
      )
      dict entry(
         string "filters"
         variant             array [
               struct {
                  string "All Files "
                  array [
                     struct {
                        uint32 0
                        string "*"
                     }
                  ]
               }
            ]
      )
      dict entry(
         string "handle_token"
         variant             string "qt385525313"
      )
      dict entry(
         string "modal"
         variant             boolean true
      )
      dict entry(
         string "multiple"
         variant             boolean false
      )
   ]
error time=1606126205.541631 sender=org.freedesktop.DBus -> destination=:1.322 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=52
   string "The name org.freedesktop.portal.Desktop was not provided by any .service files"
```
This seems to me that something is missing?

**Comment by codingtim** [comment]
It looks like commit https://github.com/FedoraQt/QGnomePlatform/commit/d5a01ea00ef49c22fa4f623495cd0d31e991a02e added the call to org.freedesktop.portal.FileChooser
If xdg-desktop-portal-gtk supplies the org.freedesktop.portal.FileChooser that would mean that xdg-desktop-portal-gtk is a required depencey for QGnomePlatform now?

**Comment by grulja** [comment]
It is not a required dependency, however it is expected you have either xdg-desktop-portal-gtk (GNOME) or xdg-desktop-portla-kde (KDE) installed when xdg-desktop-portal is available.

**Comment by codingtim** [comment]
I dont have xdg-desktop-portal installed either. So this means that xdg-desktop-portal-gtk would not be required to correctly display the dialogs?

**Comment by grulja** [comment]
Should be fixed with https://github.com/FedoraQt/QGnomePlatform/commit/ee864dfcde670b705046094cd8d810a3982ae829.
