### ISSUE TITLE
Regression on `gtk-application-prefer-dark-theme` setting?

### ISSUE THREAD

**Issue by jeffshee** [FedoraQt/QGnomePlatform#76]
Hi,

Although most applications will work fine with Adwaita-dark, some applications aren't that well supported.
**cough** WPS **cough**

For this reason, I actually want to enable the dark theme just for the native GTK application.
Previously I was able to do that, by manually set the parameter `gtk-application-prefer-dark-theme=1` in `~\.config\gtk-3.0\settings.ini` and `~\.config\gtk-4.0\settings.ini`.

However, recently I realized that it doesn't work anymore. 
It seems like some widgets are getting affected by the parameter mentioned above.
Some screenshots attached below.

OS: Fedora 33
Gnome 3.38.2

![Screenshot from 2020-12-08 11-55-04](https://user-images.githubusercontent.com/25530920/101432640-90870e80-394c-11eb-8e9b-dd1757246653.png)
![Screenshot from 2020-12-08 11-55-33](https://user-images.githubusercontent.com/25530920/101432673-9da3fd80-394c-11eb-90d5-4a838b7a75a0.png)
![Screenshot from 2020-12-08 11-59-34](https://user-images.githubusercontent.com/25530920/101432796-dd6ae500-394c-11eb-8ade-93d739aab474.png)

Thanks.

**Comment by grulja** [comment]
With https://github.com/FedoraQt/QGnomePlatform/commit/0636d3740f21b70543dd0eb323c37d9dfd130711 you should be able to fully force light or dark theme using QT_STYLE_OVERRIDE. Using gtk-application-prefer-dark-theme option will tell QGnomePlatform to use dark colors.
