### ISSUE TITLE
Dark mode is not picked up when using QT_STYLE_OVERRIDE=adwaita-dark

### ISSUE THREAD

**Issue by MeisterP** [FedoraQt/QGnomePlatform#80]
Dark mode is not picked up when using QT_STYLE_OVERRIDE=adwaita-dark and therefore the menus  are using the light theme. This used to work correctly with version 0.6.1.

QT_LOGGING_RULES="qt.qpa.qgnomeplatform.debug=true" **QT_STYLE_OVERRIDE=adwaita-dark** GoldenCheetah

qt.qpa.qgnomeplatform: Font name:  "Noto Sans"  (size  10 )
qt.qpa.qgnomeplatform: Monospace font name:  "Source Code Pro"  (size  11 )
qt.qpa.qgnomeplatform: TitleBar font name:  "Noto Sans"  (size  10 )
qt.qpa.qgnomeplatform: Cursor blink time:  1200
qt.qpa.qgnomeplatform: Double click time:  400
qt.qpa.qgnomeplatform: Long press time:  500
qt.qpa.qgnomeplatform: Double click distance:  5
qt.qpa.qgnomeplatform: Dnd drag threshold:  8
qt.qpa.qgnomeplatform: Password hint timeout:  0
qt.qpa.qgnomeplatform: Icon theme:  "Adwaita"
qt.qpa.qgnomeplatform: Theme name:  "Adwaita"
**qt.qpa.qgnomeplatform: Dark version:  no**

![celluloid-shot0002](https://user-images.githubusercontent.com/781063/109414041-0da4ab80-79b1-11eb-8b36-56e414cfb4f5.jpg)

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/QGnomePlatform/commit/0636d3740f21b70543dd0eb323c37d9dfd130711.
