### ISSUE TITLE
KeePassXC icons wrong

### ISSUE THREAD

**Issue by cooperbang** [FedoraQt/QGnomePlatform#81]
Icons in KeePassXC are wrong if no database is selected or until you open and close "Help" --> "About" window.  

According to https://github.com/keepassxreboot/keepassxc/issues/6299 this is a problem with QGnomePlatform.

**Comment by grulja** [comment]
What icon theme do you use? I cannot reproduce this issue. Does it happen with any other Qt application?

**Comment by cooperbang** [comment]
I use default Adwaita Theme (Fedora Linux 33).

QGnomePlatform Version: qgnomeplatform-0.7.0-2.fc33.x86_64

I can reproduce it by doing the following steps:

1. sudo dnf install keepassxc --> (keepassxc-2.6.4-1.fc33.x86_64)
2. open keepassxc and don´t open or create a database
3. icons are fully black or gray until "Help" --> "About" Window is not openend and closed or a database is selected/openend.

Screen recording:
http://transfer.sh/zSdMz/KeePassXC_icons.mkv

**Comment by grulja** [comment]
I will ask again, does it happen with any other Qt application? 

I have same version of keepassxc and Fedora 34 and I cannot reproduce it. Keepassxc uses a custom theme, I don't really think this is an issue in QGnomePlatform as I cannot think of anything possibly having effect on your issue.

**Comment by cooperbang** [comment]
I haven´t seen this problem with any other Qt application.

I would say it´s a problem of KeePassXC itself but they deny. The strange thing is that the icons are turning to the right ones if i click "Help" --> "About".

Maybe Fedora 34 will fix it...

**Comment by grulja** [comment]
It's interesting it doesn't happen with different platform theme. Can you try to uninstall qgnomeplatform just for a test?

**Comment by cooperbang** [comment]
If uninstalled qgnomeplatform now:

All icons are ok then - you can see it here:
http://transfer.sh/IFfoV/KeePassXC_without_qgnomeplatform.mkv

**Comment by grulja** [comment]
What if you run "keepassxc -style adwaita" while you have QGnomePlatform uninstalled?

**Comment by cooperbang** [comment]
That´s interesting. If I run it with "-style Adwaita" everything looks fine!

So what does it mean?

**Comment by grulja** [comment]
> That´s interesting. If I run it with "-style Adwaita" everything looks fine!
> 
> So what does it mean?

With QGnomePlatform installed or uninstalled?

**Comment by cooperbang** [comment]
QGnomePlatform is uninstalled:

Comparison:
`keepassxc` vs. `keepassxc -style Adwaita` while QGnomePlatform uninstalled --> http://transfer.sh/5GceV/comparison.mkv

**Comment by cooperbang** [comment]
Hi again,

I´ve discovered that the title-bar (of the "Help -> About" Window) also is missing if QGnomePlatform is installed.

Look here:

QGnomePlatform installed -> Command: `keepassxc` -> Title Bar is missing:
![qgnomeplatform_installed](https://user-images.githubusercontent.com/75366896/112439002-e55a6380-8d48-11eb-8678-a5b0d4abdcdd.png)

QGnomePlatform uninstalled -> Command: `keepassxc -syle Adwaita` -> Title Bar is displayed correctly:
![qgnomeplatform_uninstalled](https://user-images.githubusercontent.com/75366896/112439071-f6a37000-8d48-11eb-80c6-1b35cd2a6599.png)

**Comment by grulja** [comment]
The titlebar (decorations) is missing because QGnomePlatform provides decorations for them. I don't know why it didn't default to basic Qt decorations. However, I still don't have any idea why this issue happens to you, but I'm unable to reproduce it. I would also suggest to install qgnomeplatform back, as it brings better Qt integration into GNOME.

**Comment by cooperbang** [comment]
Ok, thanks. I think the problem is that the integrated themes of KeePassXC collide with QGnomePlatform.

**Comment by cooperbang** [comment]
Sorry - I´ve recognized another thing:

If I start it with `sudo keepassxc ` the icons also are correct and the titlebar decorations are here.
Only the fonts look a little bit different...

![sudo](https://user-images.githubusercontent.com/75366896/112651549-cba24480-8e4c-11eb-811d-ca0c65518672.png)

Does this help to locate the problem?

**Comment by cooperbang** [comment]
Hi, just want to tell that I have the same problem with KeePassXC icons on a freshly installed Fedora 34 Beta.

**Comment by grulja** [comment]
> Hi, just want to tell that I have the same problem with KeePassXC icons on a freshly installed Fedora 34 Beta.

I will try to install clean Fedora 34 into a VM and check what's going on. Thank you for your patience.

**Comment by grulja** [comment]
I can finally reproduce:

I tested:
1) Keepassxc with QGnomePlatform + Adwaita-qt → DOESN'T WORK
2) Keepassxc with QGnomePlatform + Breeze → DOESN'T WORK
3) Keepassxc with KDE platform theme + Breeze → DOESN'T WORK
4) Keepassxc with xcb platform (XWayland) → WORKS!!

This is most definitely not a bug in QGnomePlatform, but looks like a bug in the app itself or Qt Wayland.

**Comment by cooperbang** [comment]
Sorry for coming back again:

Is it possible that https://sourceforge.net/p/qt5ct/tickets/86/ could be a solution vor QGnomePlatform too?

**Comment by grulja** [comment]
Maybe. I will check and try.

**Comment by cooperbang** [comment]
The problem is gone now.
I´m not sure why - maybe it´s the new version of adwaita-icon-theme-40.1.1-1.fc34.noarch?

**Comment by grulja** [comment]
That's because Fedora now forces xcb platform (X11) to be used for keepassxc so it doesn't run natively on Wayland.
