### ISSUE TITLE
Maximizing/restoring Qt windows by double-click on title-bar doesn´t work (Fedora 34/Wayland)

### ISSUE THREAD

**Issue by cooperbang** [FedoraQt/QGnomePlatform#83]
Maximizing/restoring Qt windows by double-click on title-bar doesnt work in Fedora 34 (Wayland).
It needs a "double double-click" to maximize/restore the windows.

Uninstalling qgnomeplatform fixes the problem.

Problem doesn´t occur with Xorg and doesn´t occur with GTK apps.

qt5-qtwayland-5.15.2-5.fc34.x86_64                                             
gnomeplatform-0.7.1-1.fc34.x86_64

**Comment by grulja** [comment]
I have fixed this, however I missed to include this change in 0.7.1.

The change is: https://github.com/FedoraQt/QGnomePlatform/commit/7790df2a9c537e77fe450c22d490a2260480ef87

**Comment by grulja** [comment]
FYI: I will backport this to Fedora.
