### ISSUE TITLE
[Feature request] Follow system theme for open apps

### ISSUE THREAD

**Issue by julianfairfax** [FedoraQt/QGnomePlatform#85]
Hi, first off I'd like to thank you for this great tweak. It's much more convenient than manually modifying the qt theme in a file. But unfortunately this tweak still requires you to restart the app in order to update the theme. If possible it would nice if this tweak could update the theme for open apps, when the gtk the theme is changed. Thanks again!

**Comment by julianfairfax** [comment]
Sorry for closing and opening this again, would you still be up for adding this functionality? Thanks for your wonderful tweak!

**Comment by julianfairfax** [comment]
Sorry for closing and opening this again, would you still be up for adding this functionality? Thanks for your wonderful tweak!

**Comment by julianfairfax** [comment]
I don't actually know if this is possible to implement, and QGnomePlatform is already the most native way to theme Qt apps under GTK but if this is possible, it would make it even more native.

**Comment by julianfairfax** [comment]
Is any progress being made on this request? There doesn't seem to have been any activity here for a bit?

**Comment by grulja** [comment]
Hi, I'm sorry, but I haven't had time to look into this yet.

**Comment by grulja** [comment]
This is already implemented in current master. It will be part of the next release.
