### ISSUE TITLE
About Fillet

### ISSUE THREAD

**Issue by chen244** [FedoraQt/QGnomePlatform#88]
I try your new source , and it works on qt6
but I view there is no fillet when split the window on qt6
![image](https://user-images.githubusercontent.com/60290287/141786384-eb8a2fa8-dffc-4e7b-b85b-7f3e0ef351c9.png)
This is greate, but when it comes to qt5
![image](https://user-images.githubusercontent.com/60290287/141786500-7ba89cab-ae7e-492c-95ed-0ad7f0846bb0.png)
When the window is split, There is still some gap, the fillet is still, if can fix it?

**Comment by grulja** [comment]
This is unfortunately not possible to be fixed with Qt5, because it requires additional API which is only provided in Qt6, therefore there is slightly different behavior between both versions.
