### ISSUE TITLE
[RFE] Qt6: Implement QPlatformTheme::createPlatformMenu() to provide native menu in systray

### ISSUE THREAD

**Issue by Decodetalkers** [FedoraQt/QGnomePlatform#89]
Before install the qgnomeplatform
![image](https://user-images.githubusercontent.com/60290287/141965309-5547b594-debd-4f0b-a0ea-01350fcb09d7.png)
after install qgnoomeplatform
![image](https://user-images.githubusercontent.com/60290287/141965448-54692a18-733e-45ed-ba6c-4dacd205e293.png)

System is archllinux
tray extention is 
https://github.com/ubuntu/gnome-shell-extension-appindicator

This application is vlc

**Comment by chen244** [comment]
Can it help? If it can be solved..

**Comment by chen244** [comment]
I prefer the appearance can sitll.

**Comment by grulja** [comment]
This is most likely because QGnomePlatform doesn't have implementation of gtk menu, unlike the original Qt implementation.

**Comment by guihkx** [comment]
Well, I've always had QGnomePlatform installed and I'd always get the "native-looking" tray icon menu:

![image](https://user-images.githubusercontent.com/626206/142748982-818d5828-f312-4ac7-bbe4-98cbf2f4a0a0.png)

But as of QGnomePlatform 0.8.2, it looks like this (only when right-clicked, by the way):

![image](https://user-images.githubusercontent.com/626206/142749063-dbd82506-87a1-4ab3-9d49-321882ff6577.png)

I ran a git bisect against 0.8.1 and 0.8.2 and it lead me to commit 71da0a5d29ecf0503532148105f6ee509e635c73:

```
$ git bisect log
git bisect start
# good: [f75a94825224edce4ecc3d952cc819b2d5f295b4] Merge branch 'master' into 0.8
git bisect good f75a94825224edce4ecc3d952cc819b2d5f295b4
# bad: [71da0a5d29ecf0503532148105f6ee509e635c73] Drop support for QDBusTrayIcon for not being exported by Qt
git bisect bad 71da0a5d29ecf0503532148105f6ee509e635c73
# good: [313fc9ffb998e01f109f9aa612fdaa1e75302c7c] Try to fix Qt6 version which fails to load
git bisect good 313fc9ffb998e01f109f9aa612fdaa1e75302c7c
# good: [17e8b02bf7f58d5b2fb22ba9a573f0bb2fe21bdb] Bump version to 0.8.2
git bisect good 17e8b02bf7f58d5b2fb22ba9a573f0bb2fe21bdb
# first bad commit: [71da0a5d29ecf0503532148105f6ee509e635c73] Drop support for QDBusTrayIcon for not being exported by Qt
```

As a workaround, you can just stay in 0.8.1 for now.

Let me know if there's something I can do to help debug this further. Thanks.

**Comment by grulja** [comment]
Thanks. I reverted this for Qt5.
