### ISSUE TITLE
Set XCURSOR_THEME?

### ISSUE THREAD

**Issue by teohhanhui** [FedoraQt/QGnomePlatform#92]
QGnomePlatform already sets `XCURSOR_SIZE`:

https://github.com/FedoraQt/QGnomePlatform/blob/8e3752795d48b438449ff235ce91ef4ae804da4e/src/common/gnomesettings.cpp#L391

but not `XCURSOR_THEME`.

With Qt6's switch by default to Wayland, this means Qt6 apps have broken cursor theme on default GNOME desktop (Adwaita cursor theme), e.g.

https://github.com/telegramdesktop/tdesktop/issues/17457
https://github.com/telegramdesktop/tdesktop/issues/17477
https://github.com/flathub/org.telegram.desktop/issues/363

**Comment by grulja** [comment]
Fixed with https://github.com/FedoraQt/QGnomePlatform/commit/5fe754e510a6700c766302b15931a421d2658f46.
