### ISSUE TITLE
How to install Qt5ThemeSupport on Ubuntu?

### ISSUE THREAD

**Issue by locness3** [FedoraQt/QGnomePlatform#95]
Trying to build QGnomePlatform on Ubuntu 21.10 aarch64 , running `cmake ..` says it can't find `Qt5ThemeSupport`:
```
CMake Error at CMakeLists.txt:43 (find_package):
  By not providing "FindQt5ThemeSupport.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5ThemeSupport", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5ThemeSupport"
  with any of the following names:

    Qt5ThemeSupportConfig.cmake
    qt5themesupport-config.cmake

  Add the installation prefix of "Qt5ThemeSupport" to CMAKE_PREFIX_PATH or
  set "Qt5ThemeSupport_DIR" to a directory containing one of the above files.
  If "Qt5ThemeSupport" provides a separate development package or SDK, be
  sure it has been installed.
```
I couldn't find anything related in the ubuntu packages. A [google search](https://www.google.com/search?q=qt5themesupport+ubuntu) seems to say I could use the `qtbase5-private-dev` package. However, trying to install this package, apt wants to remove most of my desktop environement(s) and apps ([pastebin](https://extrait.facil.services/?6b72cd42fbd84724#3CZEwZFJJ5nHra24WeuTm1CLwVoJnjkMx6paw7Pg4JXq)).

What's the proper way, if any, to install `Qt5ThemeSupport` on ubuntu to build this?

**Comment by grulja** [comment]
Hi, I will not be able to help with Ubuntu packages, but I think you are correct with the package you need to install.

**Comment by locness3** [comment]
> but I think you are correct with the package you need to install.

Yeah, but I don't want to have my entire desktop deleted :)
