### ISSUE TITLE
[Feature request] Add support for more themes

### ISSUE THREAD

**Issue by CountOmega** [FedoraQt/QGnomePlatform#97]
First of all, hats off for making such a good program. I really enjoy it. 
It would be nice if more  GTK themes were supported, in my case Gruvbox-Dark. Maybe it is possible to let QT_STYLE_OVERRIDE reference the current theme.

**Comment by grulja** [comment]
I think this request is beyond QGnomePlatform scope. Purpose of QGnomePlatform is to read GNOME configuration and apply it to Qt applications. Having a Qt style looking as Gruvbox-Dark, we can try to apply it your Qt applications, but such a Qt style doesn't exist I guess and therefore we always fallback to Adwaita style, which is probably what most of the users will be using. You can try to use Kvantum and see if they have your theme supported. In that case Kvantum style will be applied automatically.
