### ISSUE TITLE
[Feature Request] Match new libadwaita style if on gnome

### ISSUE THREAD

**Issue by yavko** [FedoraQt/QGnomePlatform#98]
Most of gnome is switching to the new libadwaita style, it would be great to have QT match this new style to have a synchronized style everywhere!

**Comment by rafatosta** [comment]
Eagerly waiting!

**Comment by grulja** [comment]
This is more a request to Adwaita-qt project as QGnomePlatform is basically just to load all possible configurations and apply it to Qt apps. See https://github.com/FedoraQt/adwaita-qt/issues/166.

**Comment by yavko** [comment]
> This is more a request to Adwaita-qt project as QGnomePlatform is basically just to load all possible configurations and apply it to Qt apps. See [FedoraQt/adwaita-qt#166](https://github.com/FedoraQt/adwaita-qt/issues/166).

Doesn't QGnomePlatform handle the CSD and other stuff though?

**Comment by grulja** [comment]
> > This is more a request to Adwaita-qt project as QGnomePlatform is basically just to load all possible configurations and apply it to Qt apps. See [FedoraQt/adwaita-qt#166](https://github.com/FedoraQt/adwaita-qt/issues/166).
> 
> Doesn't QGnomePlatform handle the CSD and other stuff though? EDIT: This could allow for non adwaita-qt styles to still match the new GNOME style, before its done properly in adwaita-qt.

It does provide CSD, but that's the only visual element we will support. The rest is a matter of QStyle and that's what Adwaita-qt implements. We are not going to implement additional styles.

**Comment by grulja** [comment]
It's not, because CSD is implemented with Adwaita-qt library. Once Adwaita-qt is updated to match the new updated libadwaita style, QGnomePlatform will pick it automatically.

**Comment by yavko** [comment]
> It's not, because CSD is implemented with Adwaita-qt library. Once Adwaita-qt is updated to match the new updated libadwaita style, QGnomePlatform will pick it automatically.

Oh, sorry then!
